### ISSUE TITLE
teched2020-DEV164-ex5.2

### ISSUE THREAD

**Issue by tinama88** [SAP-samples/teched2020-DEV164#12]
Dear Sir, I am doing the DEV164 exercises, but after ex 5.2, I got error that I could not resolved, can you be so kind to tell me what I am missing?
![teched2020-DEV164-ex5 2](https://user-images.githubusercontent.com/75711266/105076485-f7194500-5a3f-11eb-9f41-d0217b38e180.jpg)

Thanks

**Comment by flovogt** [comment]
Hi @tinama88 ,
thanks a lot for reporting this issue. First of all: The app will run smoothly also with this error.
The reason why this error is shown is the ESLint check. Thee ESLint check can not find the global "sap".
Luckily, the package [@sapui5/ts-types](https://github.com/SAP/ui5-typescript/) offers these globals and more. If you have a look in the `package.json` of the UI5 application you'll see that the package is already added. I would recommend to update the version of the package to `1.84.4`
Now, you have to install the dependency.
Click on "Terminal" in the header and and select "New Terminal".
![image](https://user-images.githubusercontent.com/34711402/105150063-8f78fd80-5b04-11eb-8a6f-66f40618d2ef.png)
In the footer a new terminal window is opened. Execute following command `npm install`. With that the needed packages are installed.
Now, you'll get more detailed information about the ESLint state of your app.

**Comment by tinama88** [comment]
Thanks so much, Florian, for get back to me, I followed your steps and now only 1 red left, please advise me how to fix it, so I will continue the exercise?

Tina

![Annotation 2021-01-20 074812](https://user-images.githubusercontent.com/75711266/105199867-1d002180-5af4-11eb-8446-46675de5e6cd.jpg)

**Comment by flovogt** [comment]
Hi Tina,
if you close the file and reopen it again, does the error still appears?

**Comment by tinama88** [comment]
Dear Florian, you are genius, it did disappears, thanks so much for the help. I will now continue and close this issue.

Tina
