### ISSUE TITLE
Exercise 5 run error

### ISSUE THREAD

**Issue by tinama88** [SAP-samples/teched2020-DEV164#13]
Dear Florian: sorry to trouble you again, I have completed exercise 5, but when I tried to run it, I got error (screen print attached). Please advise.

![Annotation 2021-01-21 090621](https://user-images.githubusercontent.com/75711266/105385421-307cbc80-5bc8-11eb-9547-78afe96aa0ae.jpg)

Tina

**Comment by flovogt** [comment]
Hi @tinama88,
first of all. These error should not detain you continue with the exercise. Currently, the ui5-typescript support is still in beta mode (see repository https://github.com/SAP/ui5-typescript).
Sometime the ts-language server is not refreshed correctly and with that the issue pop ups again.
Feel free to repeat the steps https://github.com/SAP-samples/teched2020-DEV164/issues/12.
