### ISSUE TITLE
Regarding Extending Standard Fiori App from SAP BAS

### ISSUE THREAD

**Issue by RaghuRamNagandla** [SAP-samples/teched2020-DEV164#14]
Hello,

Could you please provide any document how to enable Standard Fiori App Tile, Group, Catalog on Launchpad Services( HANA CLOUD BTP )
As per the DEV164 exercises, I am able to deploy the App to Cloud CF Environment.
Could you please provide the Steps to Extend a Standard Fiori App.

Thanks in Advance

Kind Regards,
Raghu Ram

**Comment by flovogt** [comment]
Hi @RaghuRamNagandla,

thanks for reaching out to us.

Regarding the deployment to the Fiori Launchpad on Cloud Foundry, please have a look on following materials:
- Getting started with SAP Cloud Platform, Portal service on Cloud Foundry: https://blogs.sap.com/2019/12/20/getting-started-with-sap-cloud-platform-portal-service-on-cloud-foundry/
- Deliver Your First SAP Fiori Launchpad Site: https://developers.sap.com/mission.cp-starter-digitalexp-portal.html

Regarding the development of Fiori elements applications and how to extend them please use following materials:
- Developing Apps with SAP Fiori Elements: https://ui5.sap.com/#/topic/03265b0408e2432c9571d6b3feb6b1fd
- Extending SAP Fiori Elements Applications – What you need to know : https://blogs.sap.com/2020/06/12/extending-sap-fiori-elements-applications-what-you-need-to-know/

All the best and have fun!

**Comment by flovogt** [comment]
Closed because of inactivity.
